title: "My web dev portfolio"
author: "Ronnie Bj√∏rkelund"
email: "ronnie.bjorkelund@gmail.com"
description:
  "Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description."

# Front Matter defaults:
defaults:
  - scope:
      path: ""
      type: ""
    values:
      layout: "default"
